language: C

before_install:
- pwd
- ls
- pushd /tmp
- wget http://computation.llnl.gov/projects/floating-point-compression/download/zfp-0.5.0.tar.gz
- tar -xzf zfp-0.5.0.tar.gz
- pushd zfp-0.5.0
- make DEFS=-DBIT_STREAM_WORD_TYPE=uint8
- popd
- wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz
- tar -xzf hdf5-1.8.14.tar.gz
- pushd hdf5-1.8.14
- patch ./tools/h5repack/h5repack_parse.c /home/travis/build/LLNL/H5Z-ZFP/test/h5repack_parse.patch
- ./configure --prefix=`pwd`/my_install
- make -j4 install
- popd
- popd

install: true

script:
- make FC=gfortran CC=gcc ZFP_HOME=/tmp/zfp-0.5.0 HDF5_HOME=/tmp/hdf5-1.8.14/my_install all

